### ISSUE TITLE
State Drop Down Not Populating

### ISSUE THREAD

**Issue by mferrall** [KendraMBach/CIS556_Project#11]
The drop down menu for the state options isn't populating with the states.  This is in a fresh fetch of master.  @KendraMBach @CooperStansbury 

<img width="355" alt="screen shot 2018-12-08 at 11 56 53 am" src="https://user-images.githubusercontent.com/5091848/49688459-6477ef00-fae0-11e8-9a7b-827ec493209f.png">

**Comment by KendraMBach** [comment]
Interesting... Let me look into something.

**Comment by KendraMBach** [comment]
![image](https://user-images.githubusercontent.com/25671109/49689481-e6234900-faef-11e8-8239-21794032a818.png)

Oddly enough, I'm not seeing this issue. I am also on master, just pulled the latest, and rebuilt the project. 
What browser are you using?

**Comment by KendraMBach** [comment]
![image](https://user-images.githubusercontent.com/25671109/49689521-44e8c280-faf0-11e8-86ea-5569615d36ae.png)

Looks like it's fine for safari too? Have you rebuilt the project since pulling?

**Comment by mferrall** [comment]
Well its working now, I thought I rebuilt it correctly.  I probably found a bug in git ;)
