### ISSUE TITLE
Product w/o size can be added to the cart

### ISSUE THREAD

**Issue by mferrall** [KendraMBach/CIS556_Project#8]
I was able to add a product to the cart without specifying the size.  Is this something that could be guarded against or is that not feasible with time we have left?  Or is it done on someones local branch?

<img width="796" alt="screen shot 2018-12-03 at 10 14 42 pm" src="https://user-images.githubusercontent.com/5091848/49416812-3f365a00-f749-11e8-81a5-00953f9b187e.png">

@CooperStansbury @KendraMBach

**Comment by CooperStansbury** [comment]
Which branch are you on and when was the last pull you made?

**Comment by mferrall** [comment]
master, I just re-fetched everything to double check.  Still happening

**Comment by KendraMBach** [comment]
Thanks for pointing this out. I haven't finished all of the validation for the shopping cart, but can add that to my next branch.

**Comment by CooperStansbury** [comment]
@KendraMBach do you need explicit DB constraints on these, or is it better to handle in the logic layer?

**Comment by mferrall** [comment]
It looks like this has been taken care of now, correct?

**Comment by CooperStansbury** [comment]
Fixed. 

![image](https://user-images.githubusercontent.com/35812893/49699378-60120b80-fb9e-11e8-9902-bbafa7f2ec91.png)
